## Global configuration for metagenomics analyses (16S and shotgun)
## Copy this file and edit as needed for your study.

project:
  name: "oral-caries-study"
  sequencing_type: "16S"   # one of: 16S | shotgun
  random_seed: 1234
  threads: 8
  output_dir: "output"      # base output folder
  temp_dir: "tmp"
  first_run: false           # when true, runner will invoke setup to install pkgs, download refs, and scaffold folders

io:
  input_dir: "HF"           # folder with RAW fastq files
  metadata_csv: "metadata.csv"
  sample_pattern: "*_R{1,2}_*.fastq.gz"  # glob pattern for paired FASTQ
  cohort: null               # optional cohort name; if null, uses basename(input_dir)

setup:
  install_packages: true
  scripts_repo: null         # optional: e.g., "https://github.com/<user>/16s-metagenomics.git"
  taxonomy_urls:
    silva_train_set: null    # optional URL; if provided and file missing, will download
    silva_species: null      # optional URL; if provided and file missing, will download

metadata:
  id_column: "SampleID"     # column with unique sample IDs matching FASTQ basenames
  group_column: "Group"     # primary comparison (e.g., case/control)
  covariates: ["Age", "Sex", "Batch"]
  block_column: null         # e.g., SubjectID for matched/paired designs

filters:
  min_sample_reads: 2000     # flag samples below this threshold
  min_feature_prevalence: 0.01  # as fraction of samples
  min_feature_abundance: 1e-5    # relative abundance threshold for pruning

plots:
  dpi: 600                  # Increased for publication quality
  width: 8
  height: 6
  base_size: 14             # Larger font for readability
  theme: "classic"          # classic | minimal | bw
  color_palette: "viridis"  # okabe-ito | viridis | tableau10 | plasma
  # ranks used for composition barplots and top-N taxa
  ranks: ["Phylum", "Class", "Order", "Family", "Genus"]
  top_taxa: 10              # Reduced for cleaner plots
  heatmap_top: 25           # Top taxa for heatmap
  enable:
    alpha: true
    composition: true
    heatmap: true
    ordination: true
    tree_rectangular: true
    tree_circular: true
    per_sample_panels: false

analysis:
  alpha_metrics: ["Shannon", "Observed", "Faith"]
  beta_metrics: ["bray", "unifrac"]  # Removed aitchison (not yet implemented)
  ordination: "PCoA"        # PCoA | NMDS
  rarefaction_depth: 0       # 0 to skip rarefaction, else integer
  da_methods: ["ancombc2", "aldex2", "deseq2"]
  p_adjust: "BH"

## 16S-specific settings
amplicon:
  primers:
    forward: "GTGYCAGCMGCCGCGGTAA"   # 515F (example)
    reverse: "GGACTACNVGGGTWTCTAAT"  # 806R (example)
    region:  "V4"
  dada2:
    truncLen: [0, 0]
    maxEE: [3, 5]
    truncQ: 2
    minLen: 100
  taxonomy:
    silva_train_set: "silva_nr99_v138.1_train_set.fa"
    silva_species: "silva_species_assignment_v138.1.fa"
  phylogeny:
    build_tree: true            # requires phangorn
    max_tips: 100               # Reduced for readable trees
  functional_inference:
    method: "none"             # picrust2 | tax4fun2 | none

## Shotgun-specific settings
shotgun:
  qc:
    run_fastqc: true
    run_multiqc: true
  host_depletion:
    enabled: true
    reference: "GRCh38"
  taxonomy:
    tool: "metaphlan4"       # metaphlan4 | kraken2
  function:
    tool: "humann"           # humann
    humann_database:
      chocophlan: "chocophlan"
      uniref90: "uniref90"
  min_read_len: 50

legacy:
  run_complete_16s_script: false   # legacy mode disabled; use modular pipeline scripts
